[package]
name = "snark-setup-operator"
version = "0.1.0"
authors = ["Kobi Gurkan <kobigurk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
azure_core = { git = "https://github.com/Azure/azure-sdk-for-rust", package = "azure_core", default-features = false }
azure_storage = { git = "https://github.com/Azure/azure-sdk-for-rust", package = "azure_storage", default-features = false, features = ["blob"] }
tokio = { version = "0.2", features = [ "full" ] }
byteorder = "1.3.4"
retry = "1.1.0"
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
chrono = {version = "0.4", features = [ "serde" ] }
gumdrop = { version = "0.7" }
url = { version = "2" }
thiserror = { version = "1" }
tracing = "0.1"
tracing-appender = "0.1.1"
tracing-subscriber = "0.2"
ethers = "0.1.3"
hex = "0.4"
phase1 = { git = "https://github.com/celo-org/snark-setup", package = "phase1", rev = "06ddd77dd8b94a7414b889f69b023e3ee92a1765" }
phase1-cli = { git = "https://github.com/celo-org/snark-setup", package = "phase1-cli", rev = "06ddd77dd8b94a7414b889f69b023e3ee92a1765" }
rand = "0.7"
reqwest = { version = "0.10", features = [ "blocking", "stream" ] }
setup-utils = { git = "https://github.com/celo-org/snark-setup", package = "setup-utils", rev = "06ddd77dd8b94a7414b889f69b023e3ee92a1765" }
secrecy = { version = "0.7" }
indicatif = "0.15.0"
zexe_algebra = { git = "https://github.com/celo-org/zexe", rev = "9febfcae7804e3224118c65607d9505a7dad4b29", package = "algebra", default-features = false, features = ["bw6_761", "bls12_377"] }
openssl-sys = { version = "0.9", features = ["vendored"]}
age = { git = "https://github.com/str4d/rage", version = "0.4.0", features = [ "cli-common", "armor" ] }
bincode = "1.3"
panic-control = "0.1.4"
lazy_static = "1.4.0"
futures = "0.3"

[patch.'https://github.com/scipr-lab/zexe']
zexe_algebra_core = { git = "https://github.com/celo-org/zexe", rev = "9febfcae7804e3224118c65607d9505a7dad4b29", package = "algebra-core", default-features = false, features = ["derive"] }
zexe_algebra = { git = "https://github.com/celo-org/zexe", rev = "9febfcae7804e3224118c65607d9505a7dad4b29", package = "algebra", default-features = false, features = ["ed_on_bls12_381", "bls12_381", "bls12_377"] }
zexe_fft = { git = "https://github.com/celo-org/zexe", rev = "9febfcae7804e3224118c65607d9505a7dad4b29", package = "ff-fft", default-features = false, features = ["ed_on_bls12_381", "bls12_381", "bls12_377"] }
zexe_bench_utils = { git = "https://github.com/celo-org/zexe", rev = "9febfcae7804e3224118c65607d9505a7dad4b29", package = "bench-utils", default-features = false, features = ["ed_on_bls12_381", "bls12_381", "bls12_377"] }
zexe_r1cs_core = { git = "https://github.com/celo-org/zexe", rev = "9febfcae7804e3224118c65607d9505a7dad4b29", package = "r1cs-core", default-features = false, features = ["ed_on_bls12_381", "bls12_381", "bls12_377"] }
