name: Core
on:
  pull_request:
  push:
    branches:
      - master
env:
  RUST_BACKTRACE: 1

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt

      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
        with:
          command: fmt
          args: --all -- --check

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all --no-fail-fast
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install node and run e2e
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          . "$NVM_DIR/nvm.sh"
          . "$NVM_DIR/bash_completion"
          nvm install node
          cd e2e
          ./e2e.sh


  cross-compile:
    name: Cross compile
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Prepare out dir
        run: |
          - mkdir out

      - name: Compile for musl
        run: |
          sudo apt-get install musl-tools
          rustup target install x86_64-unknown-linux-musl
          cargo build --bin contribute --release --target x86_64-unknown-linux-musl
          cp target/x86_64-unknown-linux-musl/release/contribute out/contribute-linux
          b2sum ./target/x86_64-unknown-linux-musl/release/contribute > out/contribute-linux.hash
          cargo build --bin generate --release --target x86_64-unknown-linux-musl
          cp target/x86_64-unknown-linux-musl/release/generate out/generate-linux
          b2sum ./target/x86_64-unknown-linux-musl/release/generate > out/generate-linux.hash
          cargo build --bin contribute --release --target x86_64-unknown-linux-musl --no-default-features
          cp target/x86_64-unknown-linux-musl/release/contribute out/contribute-linux-noasm
          b2sum ./target/x86_64-unknown-linux-musl/release/contribute > out/contribute-linux-noasm.hash
          cargo build --bin generate --release --target x86_64-unknown-linux-musl --no-default-features
          cp target/x86_64-unknown-linux-musl/release/generate out/generate-linux-noasm
          b2sum ./target/x86_64-unknown-linux-musl/release/generate > out/generate-linux-noasm.hash

      - name: Compile for MacOS
        run: |
          rustup target install x86_64-apple-darwin
          git clone https://github.com/tpoechtrager/osxcross
          cd osxcross
          wget -nc https://s3.dockerproject.org/darwin/v2/MacOSX10.10.sdk.tar.xz
          mv MacOSX10.10.sdk.tar.xz tarballs/
          UNATTENDED=yes OSX_VERSION_MIN=10.7 ./build.sh
          cd ..
          PATH="$PWD/osxcross/target/bin:$PATH" CC="$PWD/osxcross/target/bin/o64-clang" CXX="$PWD/osxcross/target/bin/o64-clang++" RUSTFLAGS="$RUSTFLAGS -C linker=$PWD/osxcross/target/bin/x86_64-apple-darwin14-clang -C ar=$PWD/osxcross/target/bin/x86_64-apple-darwin14-ar" cargo build --bin contribute --release --target x86_64-apple-darwin
          cp target/x86_64-apple-darwin/release/contribute out/contribute-macos
          b2sum ./target/x86_64-apple-darwin/release/contribute > out/contribute-macos.hash
          PATH="$PWD/osxcross/target/bin:$PATH" CC="$PWD/osxcross/target/bin/o64-clang" CXX="$PWD/osxcross/target/bin/o64-clang++" RUSTFLAGS="$RUSTFLAGS -C linker=$PWD/osxcross/target/bin/x86_64-apple-darwin14-clang -C ar=$PWD/osxcross/target/bin/x86_64-apple-darwin14-ar" cargo build --bin generate --release --target x86_64-apple-darwin
          cp target/x86_64-apple-darwin/release/generate out/generate-macos
          b2sum ./target/x86_64-apple-darwin/release/generate > out/generate-macos.hash
          PATH="$PWD/osxcross/target/bin:$PATH" CC="$PWD/osxcross/target/bin/o64-clang" CXX="$PWD/osxcross/target/bin/o64-clang++" RUSTFLAGS="$RUSTFLAGS -C linker=$PWD/osxcross/target/bin/x86_64-apple-darwin14-clang -C ar=$PWD/osxcross/target/bin/x86_64-apple-darwin14-ar" cargo build --bin contribute --release --target x86_64-apple-darwin --no-default-features
          cp target/x86_64-apple-darwin/release/contribute out/contribute-macos-noasm
          b2sum ./target/x86_64-apple-darwin/release/contribute > out/contribute-macos-noasm.hash
          PATH="$PWD/osxcross/target/bin:$PATH" CC="$PWD/osxcross/target/bin/o64-clang" CXX="$PWD/osxcross/target/bin/o64-clang++" RUSTFLAGS="$RUSTFLAGS -C linker=$PWD/osxcross/target/bin/x86_64-apple-darwin14-clang -C ar=$PWD/osxcross/target/bin/x86_64-apple-darwin14-ar" cargo build --bin generate --release --target x86_64-apple-darwin --no-default-features
          cp target/x86_64-apple-darwin/release/generate out/generate-macos-noasm
          b2sum ./target/x86_64-apple-darwin/release/generate > out/generate-macos-noasm.hash
          rm -rf osxcross

      - name: Compile for MacOS M1
        run: |
          rustup install beta
          rustup +beta target install aarch64-apple-darwin
          git clone https://github.com/tpoechtrager/osxcross
          cd osxcross
          wget -nc https://celoosxcross.blob.core.windows.net/sdk/MacOSX11.0.sdk.tar.bz2
          mv MacOSX11.0.sdk.tar.bz2 tarballs/
          UNATTENDED=yes OSX_VERSION_MIN=11.0 ./build.sh
          cd ..
          PATH="$PWD/osxcross/target/bin:$PATH" CC="$PWD/osxcross/target/bin/arm64-apple-darwin20.1-clang" CXX="$PWD/osxcross/target/bin/arm64-apple-darwin20.1-clang++" RUSTFLAGS="$RUSTFLAGS -C linker=$PWD/osxcross/target/bin/arm64-apple-darwin20.1-clang -C ar=$PWD/osxcross/target/bin/arm64-apple-darwin20.1-ar" cargo +beta build --bin contribute --release --target aarch64-apple-darwin
          cp target/aarch64-apple-darwin/release/contribute out/contribute-macos-m1
          b2sum ./target/aarch64-apple-darwin/release/contribute > out/contribute-macos-m1.hash
          PATH="$PWD/osxcross/target/bin:$PATH" CC="$PWD/osxcross/target/bin/arm64-apple-darwin20.1-clang" CXX="$PWD/osxcross/target/bin/arm64-apple-darwin20.1-clang++" RUSTFLAGS="$RUSTFLAGS -C linker=$PWD/osxcross/target/bin/arm64-apple-darwin20.1-clang -C ar=$PWD/osxcross/target/bin/arm64-apple-darwin20.1-ar" cargo +beta build --bin generate --release --target aarch64-apple-darwin
          cp target/aarch64-apple-darwin/release/generate out/generate-macos-m1
          b2sum ./target/aarch64-apple-darwin/release/generate > out/generate-macos-m1.hash
          PATH="$PWD/osxcross/target/bin:$PATH" CC="$PWD/osxcross/target/bin/arm64-apple-darwin20.1-clang" CXX="$PWD/osxcross/target/bin/arm64-apple-darwin20.1-clang++" RUSTFLAGS="$RUSTFLAGS -C linker=$PWD/osxcross/target/bin/arm64-apple-darwin20.1-clang -C ar=$PWD/osxcross/target/bin/arm64-apple-darwin20.1-ar" cargo +beta build --bin contribute --release --target aarch64-apple-darwin --no-default-features
          cp target/aarch64-apple-darwin/release/contribute out/contribute-macos-m1-noasm
          b2sum ./target/aarch64-apple-darwin/release/contribute > out/contribute-macos-m1-noasm.hash
          PATH="$PWD/osxcross/target/bin:$PATH" CC="$PWD/osxcross/target/bin/arm64-apple-darwin20.1-clang" CXX="$PWD/osxcross/target/bin/arm64-apple-darwin20.1-clang++" RUSTFLAGS="$RUSTFLAGS -C linker=$PWD/osxcross/target/bin/arm64-apple-darwin20.1-clang -C ar=$PWD/osxcross/target/bin/arm64-apple-darwin20.1-ar" cargo +beta build --bin generate --release --target aarch64-apple-darwin --no-default-features
          cp target/aarch64-apple-darwin/release/generate out/generate-macos-m1-noasm
          b2sum ./target/aarch64-apple-darwin/release/generate > out/generate-macos-m1-noasm.hash
          rm -rf osxcross

      - name: Compile for Windows
        run: |
          sudo apt install gcc-mingw-w64-x86-64
          rustup target install x86_64-pc-windows-gnu
          cargo build --bin contribute --release --target x86_64-pc-windows-gnu
          cp target/x86_64-pc-windows-gnu/release/contribute out/contribute-windows.exe
          b2sum ./target/x86_64-pc-windows-gnu/release/contribute.exe > out/contribute-windows.exe.hash
          cargo build --bin generate --release --target x86_64-pc-windows-gnu
          cp target/x86_64-pc-windows-gnu/release/generate out/generate-windows.exe
          b2sum ./target/x86_64-pc-windows-gnu/release/generate.exe > out/generate-windows.exe.hash
          cargo build --bin contribute --release --target x86_64-pc-windows-gnu --no-default-features
          cp target/x86_64-pc-windows-gnu/release/contribute out/contribute-windows-noasm.exe
          b2sum ./target/x86_64-pc-windows-gnu/release/contribute.exe > out/contribute-windows-noasm.exe.hash
          cargo build --bin generate --release --target x86_64-pc-windows-gnu --no-default-features
          cp target/x86_64-pc-windows-gnu/release/generate out/generate-windows-noasm.exe
          b2sum ./target/x86_64-pc-windows-gnu/release/generate.exe > out/generate-windows-noasm.exe.hash


      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with:
          path: |
            out/**
